name = "inspire-music"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[vars]
ADMIN_PASSWORD = "change_this_to_a_secure_password"


# Bindings for KV Namespaces
# You will need to create these namespaces in your Cloudflare dashboard and update the IDs.
[[kv_namespaces]]
binding = "USERS_KV"
id = "YOUR_USERS_KV_ID"

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "YOUR_HISTORY_KV_ID"
