name = "music01"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[vars]
ADMIN_PASSWORD = "Tian@19980919"


# Bindings for KV Namespaces
# You will need to create these namespaces in your Cloudflare dashboard and update the IDs.
[[kv_namespaces]]
binding = "USERS_KV"
id = "fd57e1278c0446e6a82856148835cc86"

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "7d3998958d064ad08832f44ea4ee34aa"
